### ISSUE TITLE
Error on message receive

### ISSUE THREAD

**Issue by speters** [axel-angel/whatsapp-email-bridge#11]
Hi,

when trying to send a message from another computer with a different WhatsApp account via yowsup-cli (/message send XXXXX text), whatsapp-email-bridge fails with the following message:

```
Parsing config: config.yaml
Starting
No handlers could be found for logger "yowsup.stacks.yowstack"
Starting input thread
Connecting
<= WhatsApp: Logged in
Traceback (most recent call last):
  File "WhatsAppEmailForwarder.py", line 474, in <module>
    stack.start()
  File "WhatsAppEmailForwarder.py", line 224, in start
    self.stack.loop()
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 169, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 105, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
```

yowsup installation is git version  https://github.com/tgalal/yowsup/commit/ead19236de67f50e3e241596f15765dbc8ece6e0

**Comment by axel-angel** [comment]
I need to check if it's the new yowsup version or an internal bug. If possible, can you enable the debug mode?

**Comment by speters** [comment]
Hi,

this is the output (up to date version https://github.com/axel-angel/whatsapp-email-bridge/commit/74d37b141eeafaa57546cd125ea986035638d521 ) with debug turned on:

```
$ ./WhatsAppEmailForwarder.py --debug
Parsing config: config.yaml
Starting
No handlers could be found for logger "yowsup.stacks.yowstack"
Starting input thread
Connecting
<= WhatsApp: Logged in
Traceback (most recent call last):
  File "./WhatsAppEmailForwarder.py", line 474, in <module>
    stack.start()
  File "./WhatsAppEmailForwarder.py", line 224, in start
    self.stack.loop()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
```

It fails instantly, when there's a message wating for delivery by the Whatsapp server.

hen I now login with yowsup-cli, the waiting message gets delivered to me and I can  start whatsapp-email-bridge:

```
$ ./WhatsAppEmailForwarder.py --debug 
Parsing config: config.yaml
Starting
No handlers could be found for logger "yowsup.stacks.yowstack"
Starting input thread
Connecting
<= WhatsApp: Logged in
```

Now while this is running, I log in with yowsup-cli from another account to send a message to the whatsapp-emal-bridge account and it fails:

```
Traceback (most recent call last):
  File "./WhatsAppEmailForwarder.py", line 474, in <module>
    stack.start()
  File "./WhatsAppEmailForwarder.py", line 224, in start
    self.stack.loop()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
```

(same as before)

Installed yowsup is at https://github.com/tgalal/yowsup/commit/28e9399f6d65a3bc90f15eba9a06a0f6cdf3a6d7 (Date:   Fri Sep 11 15:45:11 2015 +0200)

```
soenke@S350E7C:~/dev/yowsup$ ./yowsup-cli version
yowsup-cli v2.0.13
Using yowsup v2.4
soenke@S350E7C:~/dev/yowsup$ git pull
Already up-to-date.
soenke@S350E7C:~/dev/yowsup$ git log
commit 28e9399f6d65a3bc90f15eba9a06a0f6cdf3a6d7
```

**Comment by axel-angel** [comment]
It seems this issue is also present in the official client. Can you try with yowsup-cli at both ends? Take a look at this https://github.com/tgalal/yowsup/issues/970 . What's the result? Try to use the dev branch as stated in the issue.

**Comment by axel-angel** [comment]
No update for 3 weeks, closing. Feel free to reopen.
