### ISSUE TITLE
Cannot get message with new yowsup

### ISSUE THREAD

**Issue by goenie** [axel-angel/whatsapp-email-bridge#12]
Hello, i updated my yowsup with the latest 
now i get this error while receiving a message

```
 File "/root/yowsup-2.4/WhatsAppEmailForwarder.py", line 474, in <module>
    stack.start()
  File "/root/yowsup-2.4/wWhatsAppEmailForwarder.py", line 224, in start
    self.stack.loop()
  File "/root/yowsup-2.4/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/root/yowsup-2.4/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/root/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/root/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/root/yowsup-2.4/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/root/yowsup-2.4/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
[root@095-097-233-251 ~]# /bin/./wazzup
Parsing config: config.yaml
Starting
No handlers could be found for logger "yowsup.stacks.yowstack"
Starting input thread
Connecting
<= WhatsApp: Logged in
Traceback (most recent call last):
  File "/root/yowsup-2.4/WhatsAppEmailForwarder.py", line 474, in <module>
    stack.start()
  File "/root/yowsup-2.4/WhatsAppEmailForwarder.py", line 224, in start
    self.stack.loop()
  File "/root/yowsup-2.4/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/root/yowsup-2.4/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/root/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/root/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/root/yowsup-2.4/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/root/yowsup-2.4/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/root/yowsup-2.4/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
```

**Comment by axel-angel** [comment]
Hello,

Thanks for reporting the issue. I haven't upgraded my yoswup recently. I'll try to fix this today.

PS: I edited your message with code markup for readability.

**Comment by goenie** [comment]
Thanks

**Comment by axel-angel** [comment]
Sorry for the delay. I just also updated my version of yowsup. The last commit is https://github.com/tgalal/yowsup/commit/92dcf0a54f663848e806411117d2f8bb1c0bda0b and everything is working fine.

On your side, can you try to "git pull" yowsup again. If it continues to fail, can you give me its commit hash and I'll try to replicate it too.

**Comment by axel-angel** [comment]
No update since 2 weeks, closing. Feel free to open again if you still have the issue.

**Comment by axel-angel** [comment]
@goenie your issue is probably the same as #13, can you git pull and try again? it should be fixed now.
