### ISSUE TITLE
Encryption prevents correct message handling (upstream)

### ISSUE THREAD

**Issue by KaiOppi** [axel-angel/whatsapp-email-bridge#13]
Hi,

i try to run whatsapp-email-bridge with gmail. all is fine.

But i try to use the app with my local exchange server an i dont work.
I can start it. But when i send a msg to the registered number i get:

```
root@wapp2mail:~/whatsapp-email-bridge-master# python WhatsAppEmailForwarder.py  --debug
Parsing config: config.yaml
Starting
No handlers could be found for logger "yowsup.stacks.yowstack"
Connecting
Starting input thread
<= WhatsApp: Logged in

Traceback (most recent call last):
  File "WhatsAppEmailForwarder.py", line 612, in <module>
    stack.start()
  File "WhatsAppEmailForwarder.py", line 234, in start
    self.stack.loop(timeout = 10, count = 1)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
```

sorry for my bad english :-/

**Comment by axel-angel** [comment]
What's the last commit of the yowsup you cloned?

**Comment by KaiOppi** [comment]
yowsup-cli v2.0.13
Using yowsup v2.4.48

yesterday installed :-)

**Comment by axel-angel** [comment]
@KaiOppi, can you try this new version? just git pull. I cannot reproduce your problem but yowsup has an issue for that: https://github.com/tgalal/yowsup/issues/690 so I just applied their fix. Try again and report your result here. Thanks.

**Comment by axel-angel** [comment]
There is a problem with the fix: it cannot send messages anymore, I don't know why yet. I need to investigate.

**Comment by axel-angel** [comment]
Actually it's better for now to keep this encryption layer, it seems to allow us to receive more messages than without.
