### ISSUE TITLE
Error on sending crash stack by email

### ISSUE THREAD

**Issue by ramod8** [axel-angel/whatsapp-email-bridge#15]
I have set up the application in its basic form. Tried a basic test and received this error when both messages are sent and received.

```
Traceback (most recent call last):
  File "WhatsAppEmailForwarder.py", line 603, in <module>
    stack.start()
  File "WhatsAppEmailForwarder.py", line 234, in start
    ownjid = self.layer.getOwnJid()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yowsup/layers/interface/interface.py", line 82, in getOwnJid
    return self.getLayerInterface(YowAuthenticationProtocolLayer).getUsername(full)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 39, in getLayerInterface
    return self.interface if YowLayerClass is None else self.__stack.getLayerInterface(YowLayerClass)
AttributeError: 'MailLayer' object has no attribute '_YowLayer__stack'
```

**Comment by axel-angel** [comment]
@ramod8 Nice catch. Should work now.

**Comment by axel-angel** [comment]
It's fixed. More than 2 weeks without any reaction, closing. Feel free to reopen.
