### ISSUE TITLE
NameError: global name 'msg' is not defined

### ISSUE THREAD

**Issue by ghost** [axel-angel/whatsapp-email-bridge#16]
Hi there. 
When sending an email to the 'template' mail folder, for example to reply to 
a WhatsApp message, WhatsAppEmailForwarder.py crashes.

Exception: global name 'msg' is not defined

Traceback (most recent call last):
  File "WhatsAppEmailForwarder.py", line 236, in start
    self.server.loop()
  File "WhatsAppEmailForwarder.py", line 418, in loop
    self.send_yowsup(dst, msg)
NameError: global name 'msg' is not defined

Tried to change dst to dest and msg to m_str:

> > >    self.send_yowsup(dest, m_str)

Then the debug will look like

got a message in MailClient's queue for: 49***********
! mail_to_txt: {test6
}
=> WhatsApp: -> 49**********_@whatsapp.**_**.de

but no message will be delivered.

**Comment by axel-angel** [comment]
Can you try with this fix? I cannot test right now but it should help.

**Comment by ghost** [comment]
No chrash anymore. But still, the message won't be delivered. The debug output is

== Server loop
== WhatsApp loop
<= IMAP: Mail id 12
== Server loop
got a message in MailClient's queue for: 49171***
! mail_to_txt: {hi3 back
}
=> WhatsApp: -> 49171***@s.whatsapp.net
== WhatsApp loop

but no 'hi3 back' shows up on the android phone.

**Comment by axel-angel** [comment]
The output of the debug seems to indicate the message was sent through yowsup, which at this point there isn't much I can do. It's probably related to this https://github.com/axel-angel/whatsapp-email-bridge/issues/13 (upstream issue: https://github.com/tgalal/yowsup/issues/1216#issuecomment-198941649 )

**Comment by ghost** [comment]
spotted also this message:
No handlers could be found for logger "axolotl.sessionbuilder"
but don't think this is the reason.

a minor tweak:
The Reply To: Field should only hold the email address.
Now it sends something like this:
Reply-To: Name <49171***@whatsapp.***.de>
But should be
Reply-To: 49171**_@whatsapp.**_.de

so you can directly reply.

**Comment by axel-angel** [comment]
However you could try yowsup with the wa16 branch and see if it works. If you have time to make it work, you can create a PR.

**Comment by axel-angel** [comment]
>  The Reply To: Field should only hold the email address.

Why? According to the RFC spec, it is valid. When you reply it should just work, what mail client are you using?

**Comment by ghost** [comment]
but the debug message shows something like malformed dst. 

It got trapped in this code below I think:

for dst in rcpttos:
            try:
                (phone,) = parse(config.get('reply'), dst)
            except TypeError:
                print "malformed dst: %s" % (dst)
                return "501 malformed recipient: %s" % (dst)

It's like the parser won't recognize this extended RFC spec.

**Comment by axel-angel** [comment]
Which mail client are you using? It's working fine in mutt for example. The client take care of stripping the display name and only sending the address part.

**Comment by ghost** [comment]
I'm using Sylpheed. But I think this stripping isn't done by many other mail clients.

**Comment by ghost** [comment]
Giving up. I can send messages with the yowsup-cli demo command and it works, but WhatsAppEmailForwarder.py messages goto nowhere.

The output of debug is 

== WhatsApp loop
<= IMAP: Mail id 15
== Server loop
got a message in MailClient's queue for: 49171***
! mail_to_txt: {hi again back
}
=> WhatsApp: -> 49171***@s.whatsapp.net
== WhatsApp loop
== Server loop

but the message won't arrive on the other side.
The wa16 branch won't work at all here.
